name: Deploy to pages

on:
  push:
    branches:
      - rrw-main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deplyment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4
